//package login_register_design;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author A. Mjeks
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        initComponents();
        //center the form
        this.setLocationRelativeTo(null);

        //create a border for the jpanel_title
        //0 border at the top
        Border jpanelTitleBorder = BorderFactory.createMatteBorder(0, 1, 1, 1, new Color(153, 0, 153));
        //set the border to the jpanelTitle
        jPanel5.setBorder(jpanelTitleBorder);

        //create a black border for the close and minimize
        Border globalBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jPanel1.setBorder(globalBorder);

        //create a black border for the close and minimize
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimazeLabel.setBorder(labelBorder);
        closeLabel.setBorder(labelBorder);

        //create a border with the color of the parent panel for the icons label to remove the move
        Border labelIconsBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 0, 153));
        profileImage.setBorder(labelIconsBorder);
        lockImage.setBorder(labelIconsBorder);

        //create a border for the username and password field
        Border txtFieldBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 0, 153));
        usernameTxt.setBorder(txtFieldBorder);
        passwordTxt.setBorder(txtFieldBorder);

        loginBtn.setBackground(new Color(0, 84, 104));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        profileImage = new javax.swing.JLabel();
        lockImage = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimazeLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        profileImage.setOpaque(true);

        lockImage.setOpaque(true);

        usernameTxt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(153, 153, 153));
        usernameTxt.setText("id number");
        usernameTxt.setToolTipText("should not exceed 13 digits");
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFocusLost(evt);
            }
        });
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        usernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTxtKeyTyped(evt);
            }
        });

        passwordTxt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordTxt.setText("password");
        passwordTxt.setToolTipText("password should not be password");
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 102, 204));
        loginBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Registered Patients:");

        registerLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        registerLabel.setText("Not registered? Create Health Record");
        registerLabel.setToolTipText("click here to create a health record");
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lockImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                                .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(66, 66, 66))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(registerLabel)
                                                .addGap(164, 164, 164))))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(profileImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lockImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );

        //set icon to the jlabel
        profileImage.setIcon(new ImageIcon("profileImage.png"));
        //set icon to the jlabel
        lockImage.setIcon(new ImageIcon("lockImage.jpg"));

        closeLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        closeLabel.setText(" X ");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });

        minimazeLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        minimazeLabel.setText(" - ");
        minimazeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimazeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimazeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimazeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimazeLabelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(76, 76, 76))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(minimazeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeLabel)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(closeLabel)
                                                .addComponent(minimazeLabel))
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        //set icon to the jlabel
        logo.setIcon(new ImageIcon("logo.jpg"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void minimazeLabelMouseEntered(java.awt.event.MouseEvent evt) {
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.MAGENTA);
        minimazeLabel.setBorder(labelBorder);
        minimazeLabel.setForeground(Color.red);
    }

    private void minimazeLabelMouseExited(java.awt.event.MouseEvent evt) {
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimazeLabel.setBorder(labelBorder);
        minimazeLabel.setForeground(Color.black);

    }

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.MAGENTA);
        closeLabel.setBorder(labelBorder);
        closeLabel.setForeground(Color.red);
    }

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {
        Border labelBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        closeLabel.setBorder(labelBorder);
        closeLabel.setForeground(Color.black);
    }

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {
        //clear the textfield on focus if the text is "username"
        if (usernameTxt.getText().trim().toLowerCase().equals("id number")) {
            usernameTxt.setText("");
            usernameTxt.setForeground(Color.black);
        }
    }

    private void usernameTxtFocusLost(java.awt.event.FocusEvent evt) {
        //if the text field is equal to username or empty
        //set the "username" text in the text field
        //on focus lost event
        if (usernameTxt.getText().trim().equals("") || usernameTxt.getText().trim().toLowerCase().equals("id number")) {
            usernameTxt.setText("id number");
            usernameTxt.setForeground(new Color(153, 153, 153));
        }
        //create a border with the color of the parent panel for the icons label to remove the move
        Border labelIconsBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 0, 153));
        profileImage.setBorder(labelIconsBorder);
    }

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {
        //clear the passwordfield on focus if the text is "password"
        //get the password text
        String pword = String.valueOf(passwordTxt.getPassword());
        if (pword.trim().toLowerCase().equals("password")) {
            passwordTxt.setText("");
            passwordTxt.setForeground(Color.black);
        }
    }

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {
        //if the password field is equal to username or empty
        //set the "password" text in the text field
        //on focus lost event
        //get the password text
        String pword = String.valueOf(passwordTxt.getPassword());

        if (pword.trim().equals("") || pword.trim().toLowerCase().equals("password")) {
            passwordTxt.setText("password");
            passwordTxt.setForeground(new Color(153, 153, 153));
        }
        //create a border with the color of the parent panel for the icons label to remove the move
        Border labelIconsBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153, 0, 153));
        lockImage.setBorder(labelIconsBorder);
    }

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {
        //set jButton background
        loginBtn.setBackground(new Color(0, 101, 183));
    }

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {
        //set jButton background
        loginBtn.setBackground(new Color(0, 84, 104));
    }

    private void minimazeLabelMouseClicked(java.awt.event.MouseEvent evt) {
        this.setState(JFrame.ICONIFIED);
    }

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        RegisterForm regForm = new RegisterForm();
        MedicalRecord medRec = new MedicalRecord();

        PreparedStatement prepState;
        ResultSet resSet;

        //get the username & password from user input
        String idNum = usernameTxt.getText();
        String password = String.valueOf(passwordTxt.getPassword());

        //create a select query to check if the username and the password exist in the database
        String query = "SELECT * FROM `patient` WHERE `id_number` = ? AND `password` = ?";
        String healthProvQuery = "SELECT * FROM `healthprovider` WHERE `idNumber` = ? AND `password` = ?";

        //show message if username or password is empty
        if (idNum.trim().equals("id number")) {
            JOptionPane.showMessageDialog(null, "Enter Your ID Number", "Empty Username", 2);
            usernameTxt.setText("id number");
            passwordTxt.setText("password");
            usernameTxt.setForeground(new Color(153, 153, 153));
            passwordTxt.setForeground(new Color(153, 153, 153));

        } else if (password.trim().equals("password")) {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
            usernameTxt.setText("id number");
            passwordTxt.setText("password");
            usernameTxt.setForeground(new Color(153, 153, 153));
            passwordTxt.setForeground(new Color(153, 153, 153));

        } else {
            try {
                //logging user
                prepState = MyCNX.getConnection().prepareStatement(query);
                prepState.setString(1, idNum);
                prepState.setString(2, password);
                resSet = prepState.executeQuery();

                //logging healthProv
                PreparedStatement prepState2 = MyCNX.getConnection().prepareStatement(healthProvQuery);
                prepState2.setString(1, idNum);
                prepState2.setString(2, password);
                ResultSet resSet2 = prepState2.executeQuery();

                if (resSet.next()) {
                    //checking if user has already logged in
                    regForm.loggedUser(idNum);
                    usernameTxt.setText("id number");
                    passwordTxt.setText("password");
                    usernameTxt.setForeground(new Color(153, 153, 153));
                    passwordTxt.setForeground(new Color(153, 153, 153));
                    MyCNX.getConnection().close();

                } else if (resSet2.next()) {
                    medRec.loggedHealthProv(idNum);
                    medRec.setVisible(true);
                    medRec.pack();
                    medRec.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    MyCNX.getConnection().close();
                    this.dispose();
                } else {
                    //error message
                    JOptionPane.showMessageDialog(null, "Invalid Username / Password", "Login Error", 2);
                    usernameTxt.setText("id number");
                    passwordTxt.setText("password");
                    usernameTxt.setForeground(new Color(153, 153, 153));
                    passwordTxt.setForeground(new Color(153, 153, 153));
                }

            } catch (SQLException ex) {
                System.out.println("SQLException: " + ex.getMessage());
            }
        }
    }

    private void registerLabelMouseEntered(java.awt.event.MouseEvent evt) {
        //change text color to purple when mouse is on text
        registerLabel.setForeground(new Color(153, 0, 153));

        //UnderLine text when hovered
        Border underline = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(153, 0, 153));
        registerLabel.setBorder(underline);
    }

    private void registerLabelMouseExited(java.awt.event.MouseEvent evt) {
        //change text color to black when mouse is on text
        registerLabel.setForeground(Color.BLACK);

        //remove underline
        registerLabel.setBorder(null);
    }

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {
        //move to the register form when the label is clicked
        RegisterForm rForm = new RegisterForm();
        rForm.setVisible(true);
        rForm.pack();
        rForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void usernameTxtKeyTyped(java.awt.event.KeyEvent evt) {
        //Only allow numbers
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login_Form().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lockImage;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimazeLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel profileImage;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration
}